shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - undici@5.29.0
catalogs:
  build:
    rolldown: 1.0.0-rc.5
  dev:
    '@actions/core': ^3.0.0
    '@antfu/eslint-config': ^7.7.2
    eslint: ^10.0.3
    nitro: 3.0.1-alpha.2
    typescript: ^5.9.3
    wait-on: ^9.0.4
    wrangler: ^4.72.0
  lib:
    '@upstash/redis': ^1.37.0
    aws4fetch: ^1.0.20
    ioredis: ^5.10.0
    skland-kit: ^0.3.4
    statocysts: ^0.11.1
    unctx: ^2.5.0
    unstorage: ^2.0.0-alpha.6
  types:
    '@types/node': ^25.5.0
